apiVersion: v1
kind: Service
metadata:
  name: springboot-productpage-service
  namespace: demo-tinfo
  labels:
    app: springboot-productpage
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30842
    protocol: TCP
    name: http
  selector:
    app: springboot-productpage
